openapi: "3.0.0"

info:
  version: 1.0.0
  title: Schema Object - Array Of Object Type Tests

servers:
  - url: http://langtoun.com/types

paths:
  /: {}

components:
  schemas:

    A1-OPT:
      type: array
      items:
        type: object
        properties:
          s1:
            type: string
          n1:
            type: number
            format: double
          i1:
            type: integer
            format: int64

    A1-REQ:
      type: array
      items:
        type: object
        required:
          - s1
        properties:
          s1:
            type: string
          n1:
            type: number
            format: double
          i1:
            type: integer
            format: int64
      minItems: 2
      maxItems: 16
