openapi: "3.0.0"

info:
  version: 1.0.0
  title: Schema Object - Array Of Object Reference Items Tests

servers:
  - url: http://langtoun.com/types

paths:

  /res:
    get:
      operationId: getRes
      parameters:
        - name: p1
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: p2
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/T1'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/T1'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/T1'

components:
  schemas:

    S1:
      type: string

    O1:
      properties:
        s1:
          $ref: '#/components/schemas/S1'
        i1:
          type: integer
          format: int64

    A1:
      items:
        $ref: '#/components/schemas/S1'

    A2:
      type: array
      items:
        $ref: '#/components/schemas/O1'




