openapi: "3.0.0"
info:
  version: 1.0.0
  title: Schema Object - Array Of Object Type Tests
servers:
  - url: http://langtoun.com/types
paths:
  /res:
    get:
      operationId: getRes
      parameters:
        - name: p1
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: p2
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/T1'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/T1'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/T1'
components:
  schemas:

    A1-OPT:
      type: array
      items:
        type: object
        properties:
          s1:
            type: string
          n1:
            type: number
            format: double
          i1:
            type: number
            format: int64

    A1-REQ:
      type: array
      items:
        type: object
        required:
          - s1
        properties:
          s1:
            type: string
          n1:
            type: number
            format: double
          i1:
            type: number
            format: int64




