openapi: "3.0.0"

info:
  version: 1.0.0
  title: Schema Object - Array Of Object Reference Items Tests

servers:
  - url: http://langtoun.com/types

paths:

  /: {}

components:
  schemas:

    S1:
      type: string

    O1:
      type: object
      properties:
        s1:
          $ref: '#/components/schemas/S1'
        i1:
          type: integer
          format: int64

    A1:
      items:
        $ref: '#/components/schemas/S1'

    A2:
      type: array
      items:
        $ref: '#/components/schemas/O1'




