openapi: "3.0.0"

info:
  version: 1.0.0
  title: Schema Object - Objects With Simple Type Properties Tests

servers:
  - url: http://langtoun.com/types

paths:
  /: {}

components:
  schemas:

    O1-OPT:
      type: object
      properties:
        s1:
          type: string
        b1:
          type: boolean
        n1:
          type: number
          format: float
        n2:
          type: number
          format: double
        i1:
          type: integer
          format: int32
        i2:
          type: integer
          format: int64
        d1:
          type: string
          format: date
        dt1:
          type: string
          format: date-time

    O1-REQ:
      type: object
      required:
        - s1
        - n1
        - i1
      properties:
        s1:
          type: string
        b1:
          type: boolean
        n1:
          type: number
          format: float
        n2:
          type: number
          format: double
        i1:
          type: integer
          format: int32
        i2:
          type: integer
          format: int64
        d1:
          type: string
          format: date
        dt1:
          type: string
          format: date-time




