openapi: "3.0.0"

info:
  version: 1.0.0
  title: Schema Object - Objects With Simple Array Properties Tests

servers:
  - url: http://langtoun.com/types

paths:
  /: {}

components:
  schemas:

    O1-OPT:
      type: object
      properties:
        s1:
          type: array
          items:
            type: string
          minItems: 0
          maxItems: 100
        b1:
          type: array
          items:
            type: boolean
          minItems: 1
          maxItems: 100
        n1:
          type: array
          items:
            type: number
            format: float
          minItems: 2
          maxItems: 100
        n2:
          type: array
          items:
            type: number
            format: double
          minItems: 3
        i1:
          type: array
          items:
            type: integer
            format: int32
        i2:
          type: array
          items:
            type: integer
            format: int64
        d1:
          type: array
          items:
            type: string
            format: date
        dt1:
          type: array
          items:
            type: string
            format: date-time

    O1-REQ:
      type: object
      required:
        - s1
        - n1
        - i1
      properties:
        s1:
          type: array
          items:
            type: string
        b1:
          type: array
          items:
            type: boolean
        n1:
          type: array
          items:
            type: number
            format: float
          maxItems: 50
        n2:
          type: array
          items:
            type: number
            format: double
        i1:
          type: array
          items:
            type: integer
            format: int32
          maxItems: 50
        i2:
          type: array
          items:
            type: integer
            format: int64
        d1:
          type: array
          items:
            type: string
            format: date
        dt1:
          type: array
          items:
            type: string
            format: date-time
