openapi: "3.0.0"
info:
  version: 1.0.0
  title: Schema Object - Simple Type Tests
servers:
  - url: http://langtoun.com/types
paths:
  /res:
    get:
      operationId: getRes
      parameters:
        - name: p1
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
        - name: p2
          in: query
          required: false
          schema:
            $ref: '#/components/schemas/T1'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/T1'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/T1'
components:
  schemas:

    S1:
      type: string
      minLength: 4
      maxLength: 16
      pattern: '^boo:.*$'
      enums:
        - 'boo:1234'
        - 'boo:874356xl'

    B1:
      type: boolean

    N1:
      type: number
      format: float
      minimum: -10.2
      maximum: 1025
      exclusiveMinimum: false
      exclusiveMaximum: true
      enum:
        - -3.728
        - 0
        - 1400

    N2:
      type: number
      format: double
      minimum: -10.2
      maximum: 1025
      exclusiveMinimum: false
      exclusiveMaximum: true
      enum:
        - -3.728
        - 0
        - 1400

    I1:
      type: integer
      format: int32
      minimum: -10
      maximum: 1025
      exclusiveMinimum: false
      exclusiveMaximum: true
      enum:
        - -3
        - 0
        - 1400

    I2:
      type: integer
      format: int64
      minimum: -10
      maximum: 1025
      exclusiveMinimum: false
      exclusiveMaximum: true
      enum:
        - -3
        - 0
        - 1400

    D1:
      type: string
      format: date

    DT1:
      type: string
      format: date-time
